[global]
    # Хранить историю метрик 1 час (по умолчанию 24 часа)
    history = 3600

    # Максимальный размер БД на диске — 200MB
    dbengine multihost disk space MB = 200

    # Интервал сбора метрик — 2 секунды (по умолчанию 1)
    update every = 2
